db.url=jdbc:mysql://localhost:3306/universidad
db.username=root
db.password=admin123
db.maximum-pool-size=10
db.connection-timeout=30000
server.port=8082
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
