db.url=jdbc:mysql://localhost:3306/universidad 
db.username=root 
db.password= 
db.maximum-pool-size=10 
db.connection-timeout=30000 
server.port=8081 
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true 
